<?php

/**
 * @file
 * Contains membership.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function membership_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the membership module.
    case 'help.page.membership':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_toolbar_alter().
 */
function membership_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'membership/toolbar';
}

/**
 * Implements hook_theme().
 */
function membership_theme() {
  $theme = [];
  $theme['membership'] = [
    'render element' => 'elements',
    'file' => 'membership.page.inc',
    'template' => 'membership',
  ];
  $theme['membership_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'membership.page.inc',
  ];
  $theme['membership_term'] = array(
    'render element' => 'elements',
    'file' => 'membership_term.page.inc',
    'template' => 'membership_term',
  );
  $theme['membership_term_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'membership_term.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function membership_theme_suggestions_membership(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#membership'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'membership__' . $sanitized_view_mode;
  $suggestions[] = 'membership__' . $entity->bundle();
  $suggestions[] = 'membership__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'membership__' . $entity->id();
  $suggestions[] = 'membership__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function membership_theme_suggestions_membership_term(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#membership_term'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'membership_term__' . $sanitized_view_mode;
  $suggestions[] = 'membership_term__' . $entity->bundle();
  $suggestions[] = 'membership_term__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'membership_term__' . $entity->id();
  $suggestions[] = 'membership_term__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
