<?php

/**
 * @file
 * Contains membership_term.module.
 */

/**
 * Implements hook_theme().
 */
function membership_term_theme() {
  $theme = [];
  $theme['membership_term'] = array(
    'render element' => 'elements',
    'file' => 'membership_term.page.inc',
    'template' => 'membership_term',
  );
  $theme['membership_term_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'membership_term.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function membership_theme_suggestions_membership_term(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#membership_term'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'membership_term__' . $sanitized_view_mode;
  $suggestions[] = 'membership_term__' . $entity->bundle();
  $suggestions[] = 'membership_term__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'membership_term__' . $entity->id();
  $suggestions[] = 'membership_term__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}


/**
 * Implements hook_cron().
 */
function membership_term_cron() {
  $last_run = \Drupal::state()->get('membership_term_cron_last', strtotime('yesterday'));
  if ($last_run + 7200 < time()) {
    \Drupal::service('membership_term.manager')->expireTerms();
    \Drupal::state()->set('membership_term_cron_last', time());
  }
}

