<?php

/**
 * @file
 * Contains membership.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function membership_term_theme() {
  $theme = [];
  $theme['membership_term'] = array(
    'render element' => 'elements',
    'file' => 'membership_term.page.inc',
    'template' => 'membership_term',
  );
  $theme['membership_term_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'membership_term.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function membership_theme_suggestions_membership_term(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#membership_term'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'membership_term__' . $sanitized_view_mode;
  $suggestions[] = 'membership_term__' . $entity->bundle();
  $suggestions[] = 'membership_term__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'membership_term__' . $entity->id();
  $suggestions[] = 'membership_term__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
