membership.membership_term_type.*:
  type: config_entity
  label: 'Membership term type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    membership_type:
      type: string
      label: "Membership Type"
    messages:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          data:
            type: field.scheduled_message.[%parent.id]
          weight:
            type: integer
          uuid:
            type: string